### ISSUE TITLE
Gatsby 3.0 "gatsby-source-takeshape" threw an error while running the sourceNodes lifecycle

### ISSUE THREAD

**Issue by beamercola** [takeshape/takeshape-gatsby#31]
## Describe the bug

`"gatsby-source-takeshape" threw an error while running the sourceNodes lifecycle`

## To Reproduce

1. `yarn add gatsby@latest`
2. `yarn build`

**Comment by beamercola** [comment]
Any updated on this?

**Comment by asprouse** [comment]
Should be resolved by #32
